language: python
python:
  # - "2.6"
  # - "2.7"
  - "3.2"
install:
  - python setup.py build
before_script:
  - git clone git://github.com/overviewer/Minecraft-Overviewer-Addons.git ~/mcoa/
  - wget -N http://s3.amazonaws.com/MinecraftDownload/minecraft.jar -P ~/.minecraft/bin/
script:
  - python overviewer.py ~/mcoa/exmaple ~/test-output --rendermodes=smooth-lighting
notifications:
  email: false
# matrix:
  # allow_failures:
    # - python: "3.2"